version: 2
jobs:
  deploy:
    docker:
    - image: circleci/node:10
    steps:
    - checkout
    - run: sudo apt -y install jq
    - run: |
        base_path='https://circleci.com/api/v1.1/project/github/nandenjin/portfolio-nuxt'
        target_branch='master'
        
        build_num=$(wget --header='Accept: application/json' --post-data='build_parameters[CIRCLE_JOB]=deploy' \
          "${base_path}/tree/${target_branch}?circle-token=${CIRCLE_TOKEN}" -O - 2>/dev/null | jq -r -e '.build_num')

        if [ "$build_num" = "" ]; then
          exit 1
        fi
        
        for i in `seq 1 10`; do
          echo "[Try ${i}] Waiting for build: ${base_path}/${build_num}"

          response=$(wget --header='Accept: application/json' "${base_path}/${build_num}?circle-token=${CIRCLE_TOKEN}" -O - 2>/dev/null)
          if [ "`echo "$response" | jq -r -e '.lifecycle'`" = "finished" ]; then
            status = $(echo "$response" | jq -r -e '.status')
            if [ "${status}" = "success" or "${status}" = "fixed" ]; then
              exit 0
            fi

            break
          fi

          if [ $i -eq 1 ]; then
            sleep 90
          else
            sleep 15
          fi
        done

        exit 1
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
