name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  request_build:
    runs-on: ubuntu-latest

    steps:
      - name: Request rebuild
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Delivery
          repo: nandenjin/nandenjin.com
          token: ${{ secrets.PERSONAL_TOKEN }}
