name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Request rebuild
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: CI
          repo: nandenjin/portfolio-nuxt
          token: ${{ secrets.PERSONAL_TOKEN }}
